# syntax = edrevo/dockerfile-plus
INCLUDE+ ./devops/Dockerfile.base
COPY ./apps/download /var/www
COPY ./devops/.CFconfig-download.json5 /opt/lucee/server/lucee-server/context/.CFConfig.json
# post deploy configure sentry logs, once extension is installed
COPY ./devops/.CFconfig-sentry.json /opt/lucee/server/lucee-server/deploy/.CFconfig-sentry.json
