# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:

  entrypoint:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  download:
    build:
      context: .
      dockerfile: devops/Dockerfile.download
    volumes:
      - ./apps/download:/var/www/
    expose:
      - 8888
    ports:
      - 8888:8888
    environment:
      - VIRTUAL_HOST=download.lucee.local
      - UPDATE_PROVIDER=${UPDATE_PROVIDER}                # defaults to prod, set UPDATE_PROVIDER=http://127.0.0.1:8889/rest/update/ in .env for local testing
      - UPDATE_PROVIDER_INT=${UPDATE_PROVIDER_INT}        # defaults to prod, set UPDATE_PROVIDER_INT=http://update:8888/rest/update/ in .env for local testing (docker)
      - EXTENSION_PROVIDER=${EXTENSION_PROVIDER}          # defaults to prod, set EXTENSION_PROVIDER=http://127.0.0.1:8889/rest/extension/ in .env for local testing
      - EXTENSION_PROVIDER_INT=${EXTENSION_PROVIDER_INT}  # defaults to prod, set EXTENSION_PROVIDER_INT=http://update:8888/rest/extension/ in .env for local testing (docker)
      - SENTRY_ENV=${SENTRY_ENV:-""}
      - SENTRY_DSN=${SENTRY_DSN:-""}
      - DEBUG=${DEBUG:-"false"}

  update:
    build:
      context: .
      dockerfile: devops/Dockerfile.update
    volumes:
      - ./apps/updateserver/:/var/www
    expose:
      - 8888
    ports:
      - 8889:8888
    environment:
      - VIRTUAL_HOST=update.lucee.local
      - S3_EXTENSION_SECRET_KEY=${S3_EXTENSION_SECRET_KEY}
      - S3_EXTENSION_ACCESS_KEY_ID=${S3_EXTENSION_ACCESS_KEY_ID}
      # optionally use a local directory for testing
      - S3_CORE_ROOT=${S3_CORE_ROOT} 
      - S3_EXTENSIONS_ROOT=${S3_EXTENSIONS_ROOT}
      - S3_BUNDLES_ROOT=${S3_BUNDLES_ROOT}
      - DOWNLOADS_URL=${DOWNLOADS_URL}
      - UPDATE_PROVIDER=${UPDATE_PROVIDER} # defaults to prod, set UPDATE_PROVIDER=http://update:8888/rest/update in .env for local testing
      - EXTENSION_PROVIDER=${EXTENSION_PROVIDER} # defaults to prod, set EXTENSION_PROVIDER=http://update:8888/rest/extension in .env for local testing
      - SENTRY_ENV=${SENTRY_ENV:-""}
      - SENTRY_DSN=${SENTRY_DSN:-""}
      - ALLOW_RELOAD=${ALLOW_RELOAD:-"true"}
      - DEBUG=${DEBUG:-"false"}