upstream tomcat_backend {
  server 127.0.0.1:8888;
  keepalive 32;
}

server {
  listen 0.0.0.0:8080 default_server;
  server_name _;
  index  index.cfm index.html index.htm;
  root   /var/www;
  server_name_in_redirect off;

  location ~* Application.cf[mc]$ {
    return 404;
  }
  location ~* /Web.cfc$ {
    return 404;
  }
  location ~* /lucee-server {
    return 404;
  }
  location ~* /CFIDE {
    return 404;
  }
  location ~* /lucee/graph.cfm {
    return 404;
  }
  location ~* ^/lucee {
    return 404;
  }

  location ~* \.(lex|pom)$ {
    try_files @lucee @lucee;
  }

  location ~* \.(cfm$|cfc$|cfm\/) {
    try_files @lucee @lucee;
  }

  location @lucee {
    proxy_pass http://tomcat_backend;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_redirect off;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_connect_timeout 600;
    proxy_send_timeout 600;
    proxy_read_timeout 600;
    send_timeout 600;
  }
}
