services:
  lucee:
    image: lucee-ai:latest
    environment:
      LUCEE_ADMIN_PASSWORD: "sfjsaiofdsnadlfsa23"
      AI_ENDPOINT: '{"class": "lucee.runtime.ai.anthropic.ClaudeEngine","custom": {"model": "claude-3-7-sonnet-20250219","temperature": "0.1","apiKey": "","connectTimeout": "10000","socketTimeout": "20000","conversationSizeLimit": "10"}}'
    volumes:
      - "./www:/var/www"
    ports:
      - "8854:8888" # tomcat
      - "8054:80" # nginx

# docker compose up -d
